name: manager
description: "yet another state management package"
publish_to: "none"
version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  package_info_plus: ^8.0.0
  states_rebuilder: ^6.4.0
  objectbox_generator: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  objectbox: ^4.0.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_native_splash: ^2.4.1
flutter:
  uses-material-design: true
