name: manager
description: "yet another state management package"
publish_to: 'none'
version: 2.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
